name: Hprofile-Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checksytle:checkstyle

      